### ISSUE TITLE
[Feature] Add Support for Cpp 17

### ISSUE THREAD

**Issue by blueloveTH** [16bit-ykiko/magic-cpp#2]
Cpp 17 is a widely used version. It is a good idea to support it.

**Comment by 16bit-ykiko** [comment]
There are some features that can only be used in C++20. For example, if you want to obtain the field name of a data member, the NTTP class template parameter, which is a C++20 feature, must be supported. Besides, Magic CPP also uses constexpr virtual functions and constexpr memory allocation, both of which were added to the standard in C++20. If I decide to switch the version to C++17, that means I need to rewrite all of these code, resulting in slower compilation and code hard to maintain.
