### ISSUE TITLE
Avoid different closure type visualized as same with some compiler.

### ISSUE THREAD

**Issue by Adttil** [16bit-ykiko/magic-cpp#9]
![QCIZ9JO YT8L38(V(N88SXG](https://github.com/16bit-ykiko/magic-cpp/assets/52402789/add99fda-f863-4118-b895-bd09a6a30aaf)
In clang, this two types visualized as same becouse they contain closure types which generate at the same location. the picture below shows that in msvc the closure type has unique id.
![DII 4PY$@ZVXRQ2VXW9DE{6](https://github.com/16bit-ykiko/magic-cpp/assets/52402789/68ea7b77-e21c-4e97-93d5-047bf8a1d0bb)

**Comment by 16bit-ykiko** [comment]
this have been resolved by [unify the representation of lambda type](https://github.com/16bit-ykiko/magic-cpp/commit/8cada17eb3f0e69ecbe898b5f915baad05705535)

Now, the lambda type has a uniform representation across different compilers, and every lambda type will be given a unique ID. For example, the code below:
```cpp
template <auto V>
struct Test{};

int main()
{
    std::cout << magic::visualize<Test<[]{}>>() << std::endl;
    std::cout << magic::visualize<Test<[]{}>>() << std::endl;
}
```
the output just like:
![lambda](https://github.com/16bit-ykiko/magic-cpp/assets/119843247/b39cbb6b-2845-4528-a808-40e72cc0574e)
